trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore ApiDevOpsDemo/ApiDevOpsDemo.csproj
  displayName: 'Restore dependencies'

- script: dotnet build ApiDevOpsDemo/ApiDevOpsDemo.csproj --configuration Release
  displayName: 'Build project'